version: '3.8'

services:
  app:
    build: .
    container_name: stonegy-auth-server
    restart: always
    ports:
      - "${PORT:-3333}:${PORT:-3333}"
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      SALT: ${SALT}
      AUTH_URL: ${AUTH_URL}
      WEBSITE_URL: ${WEBSITE_URL}
      TARGET_GAME_URL: ${TARGET_GAME_URL}
      ADMIN_KEY: ${ADMIN_KEY}
