services:
  app:
    build: .
    container_name: stonegy-auth-server
    restart: always
    ports:
      - "${PORT:-2020}:${PORT:-2020}"
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: ${PORT:-2020}
      NODE_ENV: ${NODE_ENV:-production}
      
      # Banco de Dados PostgreSQL
      DATABASE_URL: ${DATABASE_URL}
      DB_PORT: ${DB_PORT:-4264}
      SALT: ${SALT:-_stonegy_salt_2026}
      
      # URL Única Unificada
      SITE_URL: ${SITE_URL:-https://tibiaonline.klyraai.com.br}
      TARGET_GAME_URL: ${TARGET_GAME_URL:-https://stonegy-online.com}
      
      # Admin
      ADMIN_KEY: ${ADMIN_KEY:-CACADEXO_SODEXO_FILADAPUTA}
